# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "NCIP::Dancing"

views: "/home/magnus/scripts/NCIPServer/templates-norway/"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
   template_toolkit:
     start_tag: '[%'
     end_tag:   '%]'

# default MIME type for the responses.
# (See ANSI/NISO Z39.83-2-2012 Section 7.3, page 13.)
default_mime_type: "application/xml; charset='utf-8'"
